# Setup
title:               Lanyon
tagline:             'Bhavika Patel'
description:         'Software Developer | Full stack developer'
url:                 https://patelbhavika46.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bhavika Patel
  url:               https://patelbhavika46.github.io/
  email:             bhavika.patel3005@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
